version: "3.6"
services:

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tp

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80
    depends_on:
      - mariadb

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025